### ISSUE TITLE
Text Wrapping function malfunctions when wrapping string contains quotation marks.

### ISSUE THREAD

**Issue by talenelat-elin** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#47]
I was migrating to this addon from the "Wrapper meta-addon" and "editor wrap selected text with custom HTML" addons, and I encountered a possible bug when I tried to make a Text Wrapping function with the Wrap Before string being `<div style="font-size: 0px;">{{c1::.` and After string being `}}</div>`. 

The addon works as expected when I use the shortcut, but if I switch on the "show extra button" option, it displays like so: 
![Custom Wrapper bug report](https://user-images.githubusercontent.com/71895835/115077836-50e4ba80-9f1c-11eb-8f5c-4e5e21523f82.png)

---

### An alternate form of the error may appear too:
Steps to reproduce: 
1. Make a wrapping function as described above
2. Open the config of the addon
3. Without changing anything, close it using the close button at the top corner, (not the OK button)
4. Open the add window
5. Leads to this, a normal looking button in the Add Window:

![Custom Wrapper bug report](https://user-images.githubusercontent.com/71895835/115078127-c5b7f480-9f1c-11eb-8453-8698ae8257d6.png)

Upon clicking the button or using the 

The error message is: 

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-04-17 00:42:28

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<D:\Programs\Anki\decorator.pyc:decorator-gen-64>", line 2, in onBridgeCmd
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "D:\Data Storage\AnkiData\addons21\516643804\main.py", line 135, in onBridge
    return _old(self, str)
  File "aqt\editor.py", line 416, in onBridgeCmd
  File "D:\Data Storage\AnkiData\addons21\1899278645\editor\shortcuts_buttons.py", line 49, in <lambda>
    function = lambda e=editor, c=e["Setting"]: func(e, c)
  File "D:\Data Storage\AnkiData\addons21\1899278645\editor\editor_apply_categories.py", line 27, in my_wrap_helper
    before, after = beforeAfter.split(unique_string)
ValueError: not enough values to unpack (expected 2, got 1)

```
---
The wrapping function works well with strings that do not contain quotation marks. 
I can get around the issue by simply not having a gui button in the add dialog and relying on the shortcut, so it's not really an inconvenience for now, but thought it better to inform you about it anyway.

**Comment by pityu73** [comment]
I also see the same problem.
I tried this:
before `<font color="#ff5500">`  
after `<b></font></b>`
and my button doesn't work.
But If I tried other way (without quotation marks):
before `<font color=#ff5500>`  
after `<b></font></b>`
Then my button works but tooltip show this:
![image](https://user-images.githubusercontent.com/6589118/118045632-13831980-b370-11eb-88c7-c6e6e0928a75.png)
