### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by GrimPixel** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#56]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.50 (81cc5a09) Python 3.10.1 Qt 5.15.2 PyQt 5.15.6
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-01-20 21:36:13
Add-ons possibly involved: ⁨editor: apply font color, background color, custom class, custom style⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/main.py", line 336, in onOpenProfile
    self.loadProfile(self.profileDiag.closeWithoutQuitting)
  File "/usr/lib/python3.10/site-packages/aqt/main.py", line 462, in loadProfile
    gui_hooks.profile_did_open()
  File "/usr/lib/python3.10/site-packages/aqt/hooks_gen.py", line 3077, in __call__
    anki.hooks.runHook("profileLoaded")
  File "/usr/lib/python3.10/site-packages/anki/hooks.py", line 34, in runHook
    func(*args)
  File "/home/grim/.local/share/Anki2/addons21/1899278645/color_style_class_buttons.py", line 230, in prepareEditorStylesheet
    editor._html = editor_style + editor._html
AttributeError: module 'aqt.editor' has no attribute '_html'

**Comment by ijgnd** [comment]
that's because of changes in the editor in 2.1.50. That's just one area where this add-on is broken in 2.1.50 due to the improvements in 2.1.50.

@hgiesel: If you think that the 2.1.50 editor is sufficiently stable I'd appreciate it if you could adopt the editor part of this add-on: the application of the classes around selected text and the way the css is injected into the fields. I would probably fail at the moment.

I made some simple preparations in a new branch yesterday if you are already on qt6: I switched all imports from "from PyQt5..." to "from aqt.qt import ..." and the build script now builds two forms files, see https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/commit/baba5fbeccefe34149e9da55d130cf1beb8f2534

Thanks for your help and - in general - all your work on Anki itself to bring exact surrounding features into it.

**Comment by hgiesel** [comment]
Yes, updating this add-on is on my to-do list for 2.1.50... The surrounding feature is already in Anki (though not exported), and I think a built-in "inject user template CSS" PR is only a few PRs away at this point, so maybe we'll be able to squeeze it in :)

**Comment by ijgnd** [comment]
thanks @hgiesel. that's great news.

**Comment by ijgnd** [comment]
@hgiesel: Just bumping this topic. Sorry for bothering you. I know that you usually update add-ons after a final release. But this time we have a much longer beta period than usual and you seem to already have moved on to the new fields window and I guess that having a fresh memory of the editor code you wrote makes it easier to update this add-on earlier. 

And once more thanks for maintaining this add-on.

**Comment by hgiesel** [comment]
No problem. I would never complain about somebody reminding me about my todos :)

The only thing making me anxious about this project is maintaining backwards compatibility. Right now, I'm thinking it might even be wiser to rewrite the add-on from scratch, and simply make it compatible with the configurations of this add-on.

Did you have some experience updating add-ons for 2.1.50? Did you need to provide both a qt5 and qt6 version?

**Comment by ijgnd** [comment]
Thanks for your reply. When reading this keep my my coding skills in mind ...

> Did you have some experience updating add-ons for 2.1.50? Did you need to provide both a qt5 and qt6 version?

I have updated most of my add-ons to qt6. So far I haven't run into or heard of major problems. It's been mostly boring work.

I adjusted my build script so that it generates a forms5 and forms6 folder and I adjusted all the imports with `if qtmajor == 5 .. else ...`. In the custom styles add-on this meant just changing one line in the `bin/compile.sh` file. 

The other part was adjusting to the new-style PyQt scoped enums. Apparently pyqt5 got support for this new enum style around PyQt 5.11 which was already used in Anki 2.1.15. So it was some one-time work and I don't have to maintain different branches of the add-on. I have some add-ons like my fairly popular [Extended Tag Add_Edit Dialog](https://ankiweb.net/shared/info/1135507717) uploaded to ankiweb some weeks ago for anki .15+ and so far I haven't gotten bug reports related to these new-style enums.

Apart from these two well known areas I only had two or three minor problems that were quick fixes.

For the custom styles add-on I've already made the needed changes to the gui so that it works in qt6 or qt5 (at least for me in linux and windows, see [this branch](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/tree/ijgnd_prelim50) so that only the code related to the editor needs to be adjusted.

> Right now, I'm thinking it might even be wiser to rewrite the add-on from scratch, and simply make it compatible with the configurations of this add-on.

I agree that a full rewrite (i.e. removing my code and my config design) would improve this add-on. But this sounds pretty time-consuming and I very much prefer a mediocre but working add-on to none at all ... And I'm actually using this add-on a lot.

I think it should be much quicker to make minimal fixes so that in the editor wrapping with custom classes works again and that the custom css for the classes is loaded into the editor. I thought that by looking at the old code you could do a relatively quick fix for wrapping in the editor [in this file](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/blob/master/src/editor/apply_categories.py) and the webview of the editor [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/blob/master/src/webview/editor_set_css_js_for_webview.py) (where you can throw out most of the code that was related to the old rangy library) and treat the rest of the add-on as a blackbox?

> The only thing making me anxious about this project is maintaining backwards compatibility. 

I hope I don't miss anything. But as far as I see the add-on worked until .44. For .45-.49 I'd just show a message to update to .50. Since the old config is used people could downgrade to .44 or older.

**Comment by SnakeHit** [comment]
Need support for 2.1.50, Thanks for anki users
