### ISSUE TITLE
Activating "class (other)" wrap triggers exception

### ISSUE THREAD

**Issue by hgiesel** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#9]
Trying to activate a wrap of type "class (other)" triggers an exception.
This is on the version from 2020-05-14.

```
Caught exception:
Traceback (most recent call last):
  File "/Users/hgiesel/.local/share/AnkiDev/addons21/1899278645/menu.py", line 126, in <lambda>
    x.triggered.connect(lambda _, a=cat, b=se: my_highlight_helper(editor, a, b))
  File "/Users/hgiesel/.local/share/AnkiDev/addons21/1899278645/menu.py", line 35, in my_highlight_helper
    func(editor, setting)
  File "/Users/hgiesel/.local/share/AnkiDev/addons21/1899278645/editor_apply_styling_functions.py", line 115, in my_apply_span_class
    if e["Category"] == "class (other)" and e["Setting"] == _class and e["surround_with_div_tag"]:
KeyError: 'surround_with_div_tag'
```

**Comment by ijgnd** [comment]
Thanks. I should have noticed this. I just made a new version [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/releases/download/0.8/anki__editor__apply__font_color__background_color__custom_class__custom_style__2020-05-15_21-15.ankiaddon). This time I'll test it for some days before asking others about it.
